version: "3"
services: 
  # application api 
  auth-app:
    container_name: auth-app
    restart: always
    build: .
    ports: 
      - "3030:3030"
    volumes:
      - .:/app
    links:
      - db
  # database 
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: