version: "3"
services: 
  # application api 
  auth-app:
    image: auth-app
    container_name: auth-app
    restart: always
    build: .
    ports: 
      - "3030:3030"
    environment: 
      - MONGO_USER=root
      - MONGO_PASSWORD=''
      - MONGO_DATABASE=testdb
    volumes:
      - .:/app
    links:
      - db
  # database 
  db:
    image: mongo:5.0.11
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27018"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=''
      - MONGO_INITDB_DATABASE=testdb
      - MONGO_REPLICA_HOST=mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: